account:
    aws_account_id: AWS_ACCOUNT_ID
    aws_lambda_role: pywren_exec_role
    aws_region: us-west-2

lambda:
    memory : 1536
    timeout : 300
    function_name : pywren1
    
s3:
    bucket: BUCKET_NAME
    pywren_prefix: pywren.jobs

runtime:
    s3_bucket: ericmjonas-public
    s3_key: condaruntime.nomkl_sklearn.tar.gz

standalone:
    sqs_queue_name: pywren_queue
    visibility: 10
